export const types = {
  SIDEBAR: "SIDEBAR",
  SIDEBARRIGHT: "SIDEBARRIGHT",
  ACTIVETAB: "ACTIVETAB",

  ADDSTUDENT: "ADDSTUDENT",
  DELETESTUDENT: "DELETESTUDENT",
  UPDATESTUDENT: "UPDATESTUDENT",
  SETSTUDENTS: "SETSTUDENTS",

  ADDTEACHER: "ADDTEACHER",
  DELETETEACHER: "DELETETEACHER",
  UPDATETEACHER: "UPDATETEACHER",
  SETTEACHERS: "SETTEACHERS",

  ADDCOURSE: "ADDCOURSE",
  DELETECOURSE: "DELETECOURSE",
  UPDATECOURSE: "UPDATECOURSE",
  SETCOURSES: "SETCOURSES",

  SETATTENDANCE: "SETATTENDANCE",

  SETUSER: "SETUSER",
  UPDATEUSER: "UPDATEUSER",

  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",

  SETACTIVITY: "SETACTIVITY",

  ADDADMINUSER: "ADDADMINUSER",
  DELETEADMINUSER: "DELETEADMINUSER",
  UPDATEADMINUSER: "UPDATEADMINUSER",
  SETADMINUSER: "SETADMINUSER",

  ADDHOMEWORK: "ADDHOMEWORK",
  SETHOMEWORK: "SETADDHOMEWORK",
};
